version: '3.9'

services:
  probe:
    container_name: mi_probe
    image: gustavojodar/mspl:test
    command: mmt-probe -i ${INTERFACE}
    restart: unless-stopped
    network_mode: host
    volumes:
      - mi_report_storage:/opt/mmt/probe/result/report/online/:rw
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
    environment:
      MMT_SEC_5G_DOS_NGAP_INITIALUEMESSAGE_MS_LIMIT: 100
      MMT_SEC_5G_DOS_HTTP2_MS_LIMIT: 80

  mongodb:
    container_name: mi_db
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mi_mongodb_storage:/data/db:rw
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
    healthcheck:
      test: [ "CMD-SHELL", "mongo" ]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 27017:27017

  operator:
    container_name: mi_operator
    image: ghcr.io/montimage/mmt-operator:v1.7.6
    command: /opt/mmt/operator/bin/www -Xdatabase_server.host=mongodb -Xport_number=8080 -Xprobe_analysis_mode=online
    restart: unless-stopped
    ports:
      - ${OPERATOR_IP}:${OPERATOR_PORT}:8080/tcp
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - mi_report_storage:/opt/mmt/probe/result/report/online/:rw
    
volumes:
  mi_mongodb_storage:
  mi_report_storage:

networks:
  mi_metrics:
