version: '3.9'

services:
  probe:
    container_name: mi_probe
    image: gustavojodar/mspl:test
    command: mmt-probe -i ${INTERFACE}
    restart: unless-stopped
    network_mode: host
    environment:
      MMT_SEC_5G_DOS_NGAP_INITIALUEMESSAGE_MS_LIMIT: 100
      MMT_SEC_5G_DOS_HTTP2_MS_LIMIT: 80
