version: '3.9'

services:
  mongodb:
    container_name: mi_db
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mi_mongodb_storage:/data/db:rw
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
    healthcheck:
      test: [ "CMD-SHELL", "mongo" , "-c", "/etc/mongo/mongod.conf"]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 27017:27017

  operator:
    container_name: mi_operator
    image: ghcr.io/montimage/mmt-operator:v1.7.6
    command: /opt/mmt/operator/bin/www -Xdatabase_server.host=127.0.0.1 -Xdatabase_server.port=27017  -Xport_number=8080 -Xprobe_analysis_mode=online
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - mi_report_storage:/opt/mmt/probe/result/report/online/:rw
    network_mode: host

volumes:
  mi_mongodb_storage:
  mi_report_storage:

networks:
  mi_metrics:
