version: '3.9'

services:
  probe:
    container_name: mi_probe
    image: gustavojodar/mspl-enabler:probe
    command: mmt-probe -i ${INTERFACE} -Xprobe-id={PROBE-ID}
    restart: unless-stopped
    network_mode: host
    environment:
      MMT_SEC_5G_DOS_NGAP_INITIALUEMESSAGE_MS_LIMIT: 100
      MMT_SEC_5G_DOS_HTTP2_MS_LIMIT: 80  
  
  mongodb:
    container_name: mi_db
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mi_mongodb_storage:/data/db:rw
    healthcheck:
      test: [ "CMD-SHELL", "mongo" , "-c", "/etc/mongo/mongod.conf"]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 27017:27017

  operator:
    container_name: mi_operator
    image: ghcr.io/montimage/mmt-operator:v1.7.6
    command: /opt/mmt/operator/bin/www -Xinput_mode=socket -Xsocket_input.max_connections=3 -Xsocket_input.host=${OPERATOR_IP} -Xdatabase_server.host=127.0.0.1 -Xdatabase_server.port=27017  -Xport_number=${OPERATOR_PORT} -Xprobe_analysis_mode=online 
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - mi_report_storage:/opt/mmt/probe/result/report/online/:rw
    network_mode: host
  
volumes:
  mi_mongodb_storage:
  mi_report_storage:
