version: '3.9'

services:
  mongodb:
    container_name: mi_db
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mi_mongodb_storage:/data/db:rw
    healthcheck:
      test: [ "CMD-SHELL", "mongo" , "-c", "/etc/mongo/mongod.conf"]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - 27017:27017

  operator:
    container_name: mi_operator
    image: montimage/cerberus-mspl-enabler:operator
    command: /opt/mmt/operator/bin/www -Xinput_mode=socket -Xsocket_input.max_connections=3 -Xsocket_input.host=${OPERATOR_IP} -Xdatabase_server.host=127.0.0.1 -Xdatabase_server.port=27017  -Xport_number=${OPERATOR_PORT} -Xprobe_analysis_mode=online 
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://${OPERATOR_IP}:${OPERATOR_PORT}"]
        interval: 20s
        timeout: 10s
        retries: 5
    volumes:
      - mi_report_storage:/opt/mmt/probe/result/report/online/:rw
    network_mode: host

  probe:
    container_name: mi_probe
    image: montimage/cerberus-mspl-enabler:probe
    command: mmt-probe -i ${INTERFACE} -Xprobe-id=${PROBEID} -Xsocket-output.hostname=${OPERATOR_IP}
    restart: unless-stopped
    network_mode: host
    depends_on:
      operator:
        condition: service_healthy
    environment:
      MMT_SEC_5G_DOS_NGAP_INITIALUEMESSAGE_MS_LIMIT: 100
      MMT_SEC_5G_DOS_HTTP2_MS_LIMIT: 80  

  api:
    container_name: mi_api
    image: montimage/cerberus-mspl-enabler:api
    command: ./start_api.sh
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      mongodb:
        condition: service_healthy
      operator:
        condition: service_healthy

volumes:
  mi_mongodb_storage:
  mi_report_storage:
